version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  imageservice:
    image: madnificent/mu-image-service:0.0.3
    links:
      - db:database
    volumes:
      - ./data/files:/share
    restart: always
    labels:
      - "logging=true"
  file:
    image: semtech/mu-file-service:3.1.0
    links:
      - db:database
    volumes:
      - ./data/files:/share
    restart: always
    labels:
      - "logging=true"
  frontend-embed:
    image: lblod/frontend-toevla:0.10.0
    links:
      - identifier:backend
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  frontend-standalone:
    image: lblod/frontend-toevla:0.10.0-standalone
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  frontend-entry:
    image: lblod/frontend-toevla-data-entry:feature-account-management
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  identifier:
    image: semtech/mu-identifier:1.9.1
    links:
      - dispatcher:dispatcher
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
    environment:
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"shared\"},{\"variables\":[],\"name\":\"public\"},{\"variables\":[],\"name\":\"clean\"}]"
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  db:
    image: semtech/mu-authorization:feature-consistency-with-credo
    environment:
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      # INSPECT_OUTGOING_SPARQL_QUERIES: "false"
      # LOG_INCOMING_SPARQL_QUERIES: "true"
      # INSPECT_INCOMING_SPARQL_QUERIES: "false"
      # LOG_ACCESS_RIGHTS: "true"
      # INSPECT_ACCESS_RIGHTS_PROCESSING: "true"
      # LOG_DELTA_MESSAGES: "true"
      # LOG_DELTA_CLIENT_COMMUNICATION: "true"
      ERROR_ON_UNWRITTEN_DATA: "on"
      DATABASE_COMPATIBILITY: "Virtuoso"
      DATABASE_OVERLOAD_RECOVERY: "on"
      LOG_OUTGOING_SPARQL_QUERY_ROUNDTRIP: "on"
    volumes:
      - ./config/authorization:/config
    links:
      - triplestore:database
    logging: *default-logging
    restart: always
    labels:
      - "logging=true"
  triplestore:
    image: redpencil/virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  deltanotifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
    restart: always
    labels:
      - "logging=true"
  resource:
    image: semtech/mu-cl-resources
    links:
      - db:database
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    restart: always
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  project-scripts:
    image: semtech/mu-scripts:1.0.0
    volumes:
      - ./scripts/project-scripts/:/app/scripts/
    restart: "no"
  mocklogin:
    image: lblod/toevla-mock-login
    links:
      - db:database
  switchrole:
    image: lblod/toevla-switch-role
    links:
      - db:database
    labels:
      - "logging=true"
  transfer-museum:
    image: lblod/toevla-transfer-museum
    links:
      - db:database
  toevlaacmidmloginservice:
    image: lblod/toevla-acmidm-login-service:0.0.2
    links:
      - db:database
    environment:
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "4a28155a-802e-469b-87df-3b2b84f82a9e"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://qa.toegankelijk.vlaanderen.be/authorization/callback"
      DEBUG_LOG_TOKENSETS: "true"
      MU_APPLICATION_RESOURCE_BASE_URI: "http://data.toegankelijk.vlaanderen.be/"
      REQUEST_TIMEOUT: 5000
  deliver-email:
    image: redpencil/deliver-email-service:0.2.0
    environment:
      MAILBOX_URI: 'http://data.toevla.org/id/mailboxes/1'
      EMAIL_CRON_PATTERN: "* * * * *"
    links:
      - db:database
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  email-login:
    image: lblod/toevla-email-login:feature-login-support
    links:
      - db:database
    restart: always
    logging: *default-logging
