version: '3.4'

services:
  toevla:
    restart: "no"
  resource:
    restart: "no"
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
  triplestore:
    restart: "no"
    ports:
      - "8890:8890"
  resource:
    restart: "no"
