version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  imageservice:
    image: madnificent/mu-image-service:0.0.1
    links:
      - db:database
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
  file:
    image: semtech/mu-file-service:3.1.0
    links:
      - db:database
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
  frontend-standalone:
    image: lblod/frontend-toevla:0.3.1-standalone
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  frontend-entry:
    image: lblod/frontend-toevla-data-entry:0.3.1
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  identifier:
    image: semtech/mu-identifier:1.9.0
    links:
      - dispatcher:dispatcher
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
    environment:
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:latest
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  db:
    image: semtech/mu-authorization:0.6.0-beta.4
    environment:
      LOG_OUTGOING_SPARQL_QUERIES: "true"
      # INSPECT_OUTGOING_SPARQL_QUERIES: "false"
      # LOG_INCOMING_SPARQL_QUERIES: "true"
      # INSPECT_INCOMING_SPARQL_QUERIES: "false"
      # LOG_ACCESS_RIGHTS: "true"
      # INSPECT_ACCESS_RIGHTS_PROCESSING: "true"
      # LOG_DELTA_MESSAGES: "true"
      # LOG_DELTA_CLIENT_COMMUNICATION: "true"
      DATABASE_COMPATIBILITY: "Virtuoso"
      DATABASE_OVERLOAD_RECOVERY: "on"
    volumes:
      - ./config/authorization:/config
    links:
      - triplestore:database
    logging: *default-logging
    labels:
      - "logging=true"
    restart: always
  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.18.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  project-scripts:
    image: semtech/mu-scripts:1.0.0
    volumes:
      - ./scripts/project-scripts/:/app/scripts/
    restart: "no"
