version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  imageservice:
    image: madnificent/mu-image-service:0.0.3
    links:
      - db:database
    volumes:
      - ./data/files:/share
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.1.0
    links:
      - db:database
    volumes:
      - ./data/files:/share
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  frontend-embed:
    image: lblod/frontend-toevla:0.27.0
    links:
      - identifier:backend
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  frontend-standalone:
    image: lblod/frontend-toevla:0.27.0
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  frontend-entry:
    image: lblod/frontend-toevla-data-entry:0.50.0
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  identifier:
    image: semtech/mu-identifier:feature-override-vary-header
    links:
      - dispatcher:dispatcher
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
    environment:
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"shared\"},{\"variables\":[],\"name\":\"public\"},{\"variables\":[],\"name\":\"thumbnails\"},{\"variables\":[],\"name\":\"clean\"}]"
      SESSION_COOKIE_SECURE: "on"
      OVERRIDE_VARY_HEADER: "accept, cookie"
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  db:
    image: semtech/mu-authorization:0.6.0-beta.8
    environment:
      # LOG_OUTGOING_SPARQL_QUERIES: "true"
      # INSPECT_OUTGOING_SPARQL_QUERIES: "false"
      # LOG_INCOMING_SPARQL_QUERIES: "true"
      # INSPECT_INCOMING_SPARQL_QUERIES: "false"
      # LOG_ACCESS_RIGHTS: "true"
      # INSPECT_ACCESS_RIGHTS_PROCESSING: "true"
      # LOG_DELTA_MESSAGES: "true"
      # LOG_DELTA_CLIENT_COMMUNICATION: "true"
      ERROR_ON_UNWRITTEN_DATA: "on"
      DATABASE_COMPATIBILITY: "Virtuoso"
      DATABASE_OVERLOAD_RECOVERY: "on"
      # LOG_OUTGOING_SPARQL_QUERY_ROUNDTRIP: "on"
    volumes:
      - ./config/authorization:/config
    links:
      - triplestore:database
    logging: *default-logging
    restart: always
    labels:
      - "logging=true"
  triplestore:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  deltanotifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.22.0
    links:
      - db:database
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  project-scripts:
    image: semtech/mu-scripts:1.0.0
    volumes:
      - ./scripts/project-scripts/:/app/scripts/
    restart: "no"
    labels:
      - "logging=true"
    logging: *default-logging
  switchrole:
    image: lblod/toevla-switch-role:0.0.3
    links:
      - db:database
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  transfer-museum:
    image: lblod/toevla-transfer-museum:0.10.0
    links:
      - db:database
    environment:
      LOG_SPARQL_ALL: "false"
      LOG_SPARQL_UPDATES: "true"
      DEBUG_AUTH_HEADERS: "false"
    restart: always
    volumes:
      - "./config/transfer-museum/:/usr/src/app/config/"
    labels:
      - "logging=true"
    logging: *default-logging
  deliver-email:
    image: redpencil/deliver-email-service:0.2.0
    environment:
      MAILBOX_URI: 'http://data.toevla.org/id/mailboxes/1'
      EMAIL_CRON_PATTERN: "* * * * *"
    links:
      - db:database
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  email-login:
    image: lblod/toevla-email-login:0.1.1
    links:
      - db:database
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
