PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

INSERT {
  GRAPH ?accountUri {
    ?accountUri ext:hasRole <http://data.toevla.org/roles/819fde61-e678-4b1b-aaef-281297fdad14>.

    <http://data.toevla.org/roles/819fde61-e678-4b1b-aaef-281297fdad14>
      a ext:Role, ext:ValidatorRole;
      mu:uuid ?newUuid.
  }
} WHERE {
  GRAPH ?accountUri {
    ?accountUri a foaf:OnlineAccount;
      mu:uuid """REPLACE""".
    BIND ( "819fde61-e678-4b1b-aaef-281297fdad14" AS ?newUuid )
  }
}